// <auto-generated />
using HwInventory.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HwInventory.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CategoryHardware", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("categories_id");

                    b.Property<int>("HardwareId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hardware_id");

                    b.HasKey("CategoriesId", "HardwareId")
                        .HasName("pk_hardware_category");

                    b.HasIndex("HardwareId")
                        .HasDatabaseName("ix_hardware_category_hardware_id");

                    b.ToTable("hardware_category", (string)null);
                });

            modelBuilder.Entity("HardwareTag", b =>
                {
                    b.Property<int>("HardwareId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hardware_id");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tags_id");

                    b.HasKey("HardwareId", "TagsId")
                        .HasName("pk_hardware_tag");

                    b.HasIndex("TagsId")
                        .HasDatabaseName("ix_hardware_tag_tags_id");

                    b.ToTable("hardware_tag", (string)null);
                });

            modelBuilder.Entity("HwInventory.Api.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("HardwareId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hardware_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("occurred_at");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_activities");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_activities_occurred_at");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_activities_project_id");

                    b.HasIndex("HardwareId", "OccurredAt")
                        .HasDatabaseName("ix_activities_hardware_id_occurred_at");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("HwInventory.Api.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("ActivityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activity_id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<int?>("HardwareId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hardware_id");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_filename");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<string>("Sha256")
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageBackend")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_backend");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_key");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_attachments_activity_id");

                    b.HasIndex("HardwareId")
                        .HasDatabaseName("ix_attachments_hardware_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_attachments_project_id");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("HwInventory.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_slug");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("HwInventory.Api.Models.Hardware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long?>("AcquiredAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("acquired_at");

                    b.Property<long?>("ArchivedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archived_at");

                    b.Property<string>("AssetTag")
                        .HasColumnType("TEXT")
                        .HasColumnName("asset_tag");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("condition");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("TEXT")
                        .HasColumnName("cost");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("Identifiers")
                        .HasColumnType("TEXT")
                        .HasColumnName("identifiers");

                    b.Property<long?>("LastActivityAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_activity_at");

                    b.Property<long?>("LastUsedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Links")
                        .HasColumnType("TEXT")
                        .HasColumnName("links");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("PurchaseUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("purchase_url");

                    b.Property<string>("PurchasedFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("purchased_from");

                    b.Property<string>("Revision")
                        .HasColumnType("TEXT")
                        .HasColumnName("revision");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("serial_number");

                    b.Property<string>("Sku")
                        .HasColumnType("TEXT")
                        .HasColumnName("sku");

                    b.Property<string>("Specs")
                        .HasColumnType("TEXT")
                        .HasColumnName("specs");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<long?>("WarrantyExpiresAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("warranty_expires_at");

                    b.HasKey("Id")
                        .HasName("pk_hardware");

                    b.HasIndex("ArchivedAt")
                        .HasDatabaseName("ix_hardware_archived_at");

                    b.HasIndex("LastActivityAt")
                        .HasDatabaseName("ix_hardware_last_activity_at");

                    b.HasIndex("LastUsedAt")
                        .HasDatabaseName("ix_hardware_last_used_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_hardware_status");

                    b.ToTable("hardware", (string)null);
                });

            modelBuilder.Entity("HwInventory.Api.Models.HardwareConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("ActivityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activity_id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<int>("HardwareId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hardware_id");

                    b.Property<long?>("InstalledAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("installed_at");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_current");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_hardware_configs");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_hardware_configs_activity_id");

                    b.HasIndex("HardwareId", "Kind", "IsCurrent")
                        .HasDatabaseName("ix_hardware_configs_hardware_id_kind_is_current");

                    b.ToTable("hardware_configs", (string)null);
                });

            modelBuilder.Entity("HwInventory.Api.Models.HardwareProject", b =>
                {
                    b.Property<int>("HardwareId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hardware_id");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.HasKey("HardwareId", "ProjectId")
                        .HasName("pk_hardware_projects");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_hardware_projects_project_id");

                    b.ToTable("hardware_projects", (string)null);
                });

            modelBuilder.Entity("HwInventory.Api.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<long?>("DueAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("due_at");

                    b.Property<int>("HardwareId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hardware_id");

                    b.Property<long>("LoanedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loaned_at");

                    b.Property<string>("LoanedTo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("loaned_to");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<long?>("ReturnedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("returned_at");

                    b.HasKey("Id")
                        .HasName("pk_loans");

                    b.HasIndex("DueAt")
                        .HasDatabaseName("ix_loans_due_at");

                    b.HasIndex("HardwareId")
                        .HasDatabaseName("ix_loans_hardware_id");

                    b.HasIndex("ReturnedAt")
                        .HasDatabaseName("ix_loans_returned_at");

                    b.ToTable("loans", (string)null);
                });

            modelBuilder.Entity("HwInventory.Api.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long?>("ArchivedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archived_at");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Links")
                        .HasColumnType("TEXT")
                        .HasColumnName("links");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("priority");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long?>("TargetDate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("ArchivedAt")
                        .HasDatabaseName("ix_projects_archived_at");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_slug");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_projects_status");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("HwInventory.Api.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("CategoryHardware", b =>
                {
                    b.HasOne("HwInventory.Api.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hardware_category_categories_categories_id");

                    b.HasOne("HwInventory.Api.Models.Hardware", null)
                        .WithMany()
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hardware_category_hardware_hardware_id");
                });

            modelBuilder.Entity("HardwareTag", b =>
                {
                    b.HasOne("HwInventory.Api.Models.Hardware", null)
                        .WithMany()
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hardware_tag_hardware_hardware_id");

                    b.HasOne("HwInventory.Api.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hardware_tag_tags_tags_id");
                });

            modelBuilder.Entity("HwInventory.Api.Models.Activity", b =>
                {
                    b.HasOne("HwInventory.Api.Models.Hardware", "Hardware")
                        .WithMany("Activities")
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activities_hardware_hardware_id");

                    b.HasOne("HwInventory.Api.Models.Project", "Project")
                        .WithMany("Activities")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_activities_projects_project_id");

                    b.Navigation("Hardware");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HwInventory.Api.Models.Attachment", b =>
                {
                    b.HasOne("HwInventory.Api.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_attachments_activities_activity_id");

                    b.HasOne("HwInventory.Api.Models.Hardware", "Hardware")
                        .WithMany()
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_attachments_hardware_hardware_id");

                    b.HasOne("HwInventory.Api.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_attachments_projects_project_id");

                    b.Navigation("Activity");

                    b.Navigation("Hardware");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HwInventory.Api.Models.Category", b =>
                {
                    b.HasOne("HwInventory.Api.Models.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HwInventory.Api.Models.HardwareConfig", b =>
                {
                    b.HasOne("HwInventory.Api.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_hardware_configs_activities_activity_id");

                    b.HasOne("HwInventory.Api.Models.Hardware", "Hardware")
                        .WithMany("Configs")
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hardware_configs_hardware_hardware_id");

                    b.Navigation("Activity");

                    b.Navigation("Hardware");
                });

            modelBuilder.Entity("HwInventory.Api.Models.HardwareProject", b =>
                {
                    b.HasOne("HwInventory.Api.Models.Hardware", "Hardware")
                        .WithMany("HardwareProjects")
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hardware_projects_hardware_hardware_id");

                    b.HasOne("HwInventory.Api.Models.Project", "Project")
                        .WithMany("HardwareProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hardware_projects_projects_project_id");

                    b.Navigation("Hardware");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HwInventory.Api.Models.Loan", b =>
                {
                    b.HasOne("HwInventory.Api.Models.Hardware", "Hardware")
                        .WithMany("Loans")
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loans_hardware_hardware_id");

                    b.Navigation("Hardware");
                });

            modelBuilder.Entity("HwInventory.Api.Models.Hardware", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Configs");

                    b.Navigation("HardwareProjects");

                    b.Navigation("Loans");
                });

            modelBuilder.Entity("HwInventory.Api.Models.Project", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("HardwareProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
